# Generated by Django 5.2.5 on 2025-08-29 08:17

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Event Types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='users', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('profile_pic', models.ImageField(default='profile/default_profile.jpg', upload_to='profile/')),
                ('address', models.CharField(max_length=200)),
                ('birth_day', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_venue_owner', models.BooleanField(default=False)),
                ('ia_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'User Profile',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VenueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Venue Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.CharField(max_length=200)),
                ('venue_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('venue_email', models.EmailField(max_length=254, unique=True)),
                ('venue_website', models.URLField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL)),
                ('venue_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='venues_type', to='event_app.venuetype')),
            ],
            options={
                'db_table': 'Venues',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VenueStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_venue_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_staffs', to='event_app.venue')),
            ],
            options={
                'db_table': 'Venue Staffs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_day', models.IntegerField()),
                ('event_month', models.IntegerField()),
                ('event_year', models.IntegerField()),
                ('event_time', models.TimeField()),
                ('event_poster', models.ImageField(upload_to='event_poster/')),
                ('event_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event_app.venue')),
                ('event_manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='managers', to='event_app.venuestaff')),
            ],
            options={
                'db_table': 'Events',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
