# Generated by Django 5.2.5 on 2025-09-05 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueStaffMember',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_venue_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_staffs', to='event_app.venue')),
            ],
            options={
                'db_table': 'Venue Staff Members',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='event_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='managers', to='event_app.venuestaffmember'),
        ),
        migrations.DeleteModel(
            name='VenueStaff',
        ),
    ]
