# Generated by Django 5.2.5 on 2025-09-06 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_event_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalTickets',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='events', serialize=False, to='event_app.event')),
                ('total_tickets', models.PositiveIntegerField()),
                ('sold_tickets', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'Event Ticket',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_type', to='event_app.eventtype'),
        ),
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_ticekts', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
                ('booked_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_event', to='event_app.event')),
            ],
            options={
                'db_table': 'Booking',
                'managed': True,
                'unique_together': {('booked_by', 'booked_event')},
            },
        ),
    ]
