# Generated by Django 5.2.5 on 2025-09-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_totaltickets_alter_event_event_type_bookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaltickets',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tickets', serialize=False, to='event_app.event'),
        ),
    ]
