# Generated by Django 5.2.5 on 2025-09-06 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_alter_totaltickets_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='booked_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='event_app.event'),
        ),
    ]
