# Generated by Django 5.2.5 on 2025-09-07 07:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_alter_bookevent_booked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
